services:
  database:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=''
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
volumes:
  pgdata: